[package]
name = "jaspy-pinger"
version = "2.2.0"
authors = ["Antti Tönkyrä <daedalus@pingtimeout.net>"]

[dependencies]
config = "0.10.1"
oping = "0.4.0"
reqwest = { version = "0.11.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
