// <auto-generated />
using Jaspy.Switchmaster.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Jaspy.Switchmaster.Migrations
{
    [DbContext(typeof(SwitchmasterDbContext))]
    [Migration("20190602175745_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Jaspy.Switchmaster.Data.Entities.Switch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Configured");

                    b.Property<int>("DeployState");

                    b.Property<string>("Fqdn");

                    b.HasKey("Id");

                    b.ToTable("Switches");
                });
#pragma warning restore 612, 618
        }
    }
}
